config/routes.rb
Rails.application.routes.draw do
  resources :productos
  devise_for :users
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :producto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]
before_action :authenticate_user!
  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to producto_url(@producto), notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:title, :image, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectOne</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "reutilizable/barra" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
    <%= image_tag "", size:"300x300" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id,value: current_user.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <p>
    <strong>Title:</strong>
    <%= producto.title %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= producto.image %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= producto.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= producto.user_id %>
  </p>

</div>

app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Show this producto", @producto %> |
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Productos</h1>

<div id="productos">
  <% @productos.each do |producto| %>
    <%= render producto %>
    <p>
      <%= link_to "Show this producto", producto %>
    </p>
  <% end %>
</div>

<%= link_to "New producto", new_producto_path %>

app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div>
  <%= link_to "Edit this producto", edit_producto_path(@producto) %> |
  <%= link_to "Back to productos", productos_path %>

  <%= button_to "Destroy this producto", @producto, method: :delete %>
</div>

app/views/reutilizable/_barra.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">PROYECT ONE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", homes_index_path, class:"nav-link active" %>
          </li>           
          <% if user_signed_in? %>          
          <li class="nav-item">
            <%= link_to "Salir", destroy_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Editar Usuario", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Publicar Producto", new_producto_path, class:"nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Registrarce", new_user_registration_path, class:"nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>